drop table if exists sale5;
create table sale5 (
    product_sale_id serial primary key,
    sale_year integer,
    sale_month integer,
    sale_date timestamp,
    seller_code_PH varchar(16),
    seller_agent_historical_level varchar(16),
    seller_agent_business_area_small varchar(16),
    seller_business_area varchar(16),
    seller_sale_area varchar(16),
    seller_province varchar(16),
    seller_city varchar(16),
    seller_city_level integer,
    purchaser_code_SFE varchar(16),
    purchaser_code_PH varchar(16),
    purchaser_business_area varchar(16),
    purchaser_sale_area varchar(16),
    purchaser_sale_area_2 varchar(16),
    purchaser_province varchar(16),
    purchaser_city varchar(16),
    purchaser_city_level integer,
    purchaser_admin_code varchar(16),
    purchaser_county varchar(16),
    purchaser_SFE_terminal_level varchar(16),
    purchaser_property varchar(16),
    purchaser_category varchar(16),
    purchaser_agent_current_level varchar(16),
    purchaser_agent_historical_level varchar(16),
    purchaser_is_chain_head boolean,
    purchaser_is_target_terminal boolean,
    purchaser_is_ticket_business boolean,
    product_code varchar(16),
    product_group varchar(16),
    product_line varchar(16),
    batch_number varchar(64),
    sale_amount_factory decimal(12, 2),
    is_cross_business_area boolean,
    is_cross_province boolean,
    is_daily_data boolean,
    method_data_collect varchar(16),
    method_real_collect varchar(16),
    method_purchaser_manage varchar(16),
    is_sub_company boolean,
    upstream_company_corporation varchar(64),
    upstream_company varchar(512)
);
